15/03/2018 08:15:14 | SyncInvokeChargerLesTournees | La référence d'objet n'est pas définie à une instance d'un objet.

15/03/2018 08:47:43 | LicenceOK | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

15/03/2018 08:49:31 | LicenceOK | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

15/03/2018 08:54:55 | SyncInvokeValiderCreationFactureIsole | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

15/03/2018 10:24:40 | LicenceOK | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

15/03/2018 10:31:01 | SyncInvokeValiderCreationFactureIsole | Une erreur s'est produite lors de l'exécution de la définition de la commande. Pour plus de détails, consultez l'exception interne.

15/03/2018 14:27:09 | LicenceOK | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

15/03/2018 14:29:23 | LicenceOK | La référence d'objet n'est pas définie à une instance d'un objet.

15/03/2018 15:14:07 | LicenceOK | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

15/03/2018 15:28:16 | LicenceOK | Enregistrement annulé :
Une erreur liée au réseau ou spécifique à l'instance s'est produite lors de l'établissement d'une connexion à SQL Server. Le serveur est introuvable ou n'est pas accessible. Vérifiez que le nom de l'instance est correct et que SQL Server est configuré pour autoriser les connexions distantes. (provider: Named Pipes Provider, error: 40 - Impossible d'ouvrir une connexion à SQL Server)

15/03/2018 17:40:49 | LicenceOK | Enregistrement annulé :
Expiration du délai d'attente. Le délai d'attente s'est écoulé avant obtention d'une connexion du pool. Ceci est probablement dû au fait que toutes les connexions regroupées sont en cours d'utilisation et que la taille maximale du pool a été atteinte.

15/03/2018 18:40:14 | SyncInvokeChargerRubrique | ChargerRubrique :Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:16 | SyncInvokeChargerPuissanceSouscrite | Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:21 | SyncInvokeRetourneTousApplicationTaxe | Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:21 | SyncInvokeChargerForfait | Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:21 | SyncInvokeChargerTousMois | Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:22 | SyncInvokeChargerCommune | Échec du fournisseur sous-jacent sur Open.

15/03/2018 18:40:22 | SyncInvokeChargerLesQartiers | La référence d'objet n'est pas définie à une instance d'un objet.

